### ISSUE TITLE
Für Composer freigeben

### ISSUE THREAD

**Issue by jenda77** [davidenke/newsletter_content#11]
Hallo, 

leider kann man sich über den Composer nur die veraltete Version installieren. Es wäre super, wenn man direkt auf den Ordner hier zugreifen könnte, um die neuste Version installieren zu können. 

Liebe Grüße,

Jan

<img width="945" alt="snimek obrazovky 2015-07-07 v 8 29 10 1" src="https://cloud.githubusercontent.com/assets/3715050/8540045/57ca2b8e-2482-11e5-835d-d6ad26ea1f93.png">

**Comment by davidenke** [comment]
Hallo Jan,

ich arbeite eher selten mit dem Composer-Client. Ich schau mal, wie ich die aktuellen Versionen rein bekomme.
Hättest du einen Tipp, hast du bereits Erfahrungen damit gemacht?

**Comment by jenda77** [comment]
Hallo David, 

leider kenne ich mich da auch nicht gut aus. Das tut mir leid, sonst hätte ich mich gerne an der Entwicklung beteiligt - das will ich noch erlernen, um mehr eigene Lösungen für meine Kunden anbieten. Vielleicht könntest du aber einen der Contao-Entwickler fragen. Ich finde Patric von https://github.com/patric-eberle sehr nett, kompetent, schnell und hilfsbereit. Hoffentlich kann er dir helfen. 

Liebe Grüße,
Jan

**Comment by jenda77** [comment]
Schau mal, das habe ich gefunden http://de.contaowiki.org/Composer/Tutorial:_Extension_für_Composer_fit_machen

**Comment by jenda77** [comment]
Hallo, hat sich etwas ergeben? Leider wird die neueste Version immer noch nicht über Composer angeboten.

**Comment by matzke** [comment]
unter https://packagist.org/ kannst du einen Account anlegen und via "submit" die URL des git repos (git@github.com:davidenke/newsletter_content.git) eintragen

**Comment by davidenke** [comment]
s. https://packagist.org/packages/davidenke/newsletter_content
