### ISSUE TITLE
Link from the contao-legacy to your repository and the last version from your repository in contao-legacy

### ISSUE THREAD

**Issue by jenda77** [davidenke/newsletter_content#17]
I have problems with the installation. When I install it from the contao-legacy/newsletter_content repository, there is only the 0.5. version. But in your repository there is the 0.13.x version. Could you update it and connect it with your repository, please?

**Comment by davidenke** [comment]
I have no influence to the contao-legacy service. Install directly from GitHub, from the default extension repository in Contao or manually. There is no composer support yet.
