### ISSUE TITLE
Installation: Wrong

### ISSUE THREAD

**Issue by jenda77** [davidenke/newsletter_content#18]
When I try to install your extension through the normal extension catalog the structure of your module is wrong 
<img width="583" alt="snimek obrazovky 2016-01-25 v 15 44 09" src="https://cloud.githubusercontent.com/assets/3715050/12553989/b23b199c-c37a-11e5-979f-8b3535992394.png">

**Comment by davidenke** [comment]
Sorry, my fault. Try it again with the current ER build, please.
Btw.: I noticed, that there is an GitHub Webhook deploying the latest release to Packagist to provide the extension through composer. I pinned the latest tag as release, it should align the deployment now.
