### ISSUE TITLE
4.4 compatibility

### ISSUE THREAD

**Issue by jankout** [davidenke/newsletter_content#28]
Hello, I would like to ask you whether you are planing to make your extension compatible with the newest Contao 4.4.x and with PHP 7.x? It would be great.

**Comment by davidenke** [comment]
@jankout For now I had no plans to maintain this extension any more. Since there are so many requests on this I would think about reviewing pull requests. As mentioned in the readme it would be nice if someone would participate more into developing this extension.

**Comment by fritzmg** [comment]
See https://github.com/davidenke/newsletter_content/pull/32
