### ISSUE TITLE
Bilder automatisch verkleinert

### ISSUE THREAD

**Issue by Marco-Both** [davidenke/newsletter_content#3]
Hallo,

ich verwende Contao 3.3.5 und habe newsletter_content über die Erweiterungsverwaltung installiert.

Über das Textelement kann ich Text und Bild kombinieren. Leider wird das Bild ab einer gewissen Größe automatisch verkleinert ausgegeben. Das Layout bietet den Platz.

Bilder die über den Editor eingefügt werden sind später nicht in der E-Mail. 

Wie kann ich das beheben?

LG

**Comment by davidenke** [comment]
Hey, ist das in der aktuellen [Version 0.0.11](https://github.com/davidenke/newsletter_content/tree/0.0.11) noch vakant?

**Comment by davidenke** [comment]
closed while waiting for feedback
