### ISSUE TITLE
PHP 7.1 or 7.2 compatibility

### ISSUE THREAD

**Issue by jankout** [davidenke/newsletter_content#31]
Hello, 

unfortunately, your extension does not work with PHP 7.1 or higher. Do you have a solution for quick fix I can do by myself? Thank you. 

When I try to send me a test newsletter I get this error message: 

`Fatal error: Cannot use 'String' as class name as it is reserved in /mnt/web221/e3/75/54138075/htdocs/system/modules/core/library/Contao/String.php on line 28`

**Comment by davidenke** [comment]
should be fixed with #32.
