### ISSUE TITLE
Mehrsprachigkeit und der Inserttag {{iflng}} funktioniert nicht

### ISSUE THREAD

**Issue by jenda77** [davidenke/newsletter_content#5]
Hallo, 

ich versuche die Kopfzeile mehrsprachig zu gestalten. Leider wird der Inserttag {{iflng}} ignoriert. Kann man da etwas machen oder geht es generell nicht? 

Liebe Grüße,

Jan

**Comment by davidenke** [comment]
Inserttags werden geparst, allerdings kann ein {{iflng}} nicht erkannt werden. Im Gegensatz zu einer Website, bei der der Useragent erkenntlich macht, welche Sprache der Nutzer verwendet, werden HTML-Newsletter bereits gerendert versendet.

**Comment by jenda77** [comment]
Danke, verstehe. Jetzt ist es zum Glück möglich dank der individuellen Vorlagen. Danke für die schnelle Einbindung dieser Funktion. :+1:
