### ISSUE TITLE
Verschiedene Template-Ordner und individuelle Templates nutzen

### ISSUE THREAD

**Issue by jenda77** [davidenke/newsletter_content#6]
Um die Mehrsprachigkeit zu nutzen, dachte ich, dass ich es mit verschiedenen Ordnern für die jeweilige Sprache und dann mit den dazu gehörigen Templates lösen kann. Allerdings unterstützt diese Erweiterung keine Templateordner sowie keine eigene Templates. Es wäre super, wenn man die Möglichkeiten haben könnte, weil es schon ein Standard ist und für die mehrsprachigen Seiten wesentlich ist. Geht es bitte? Ich würde mich sehr freuen. :-) 

Liebe Grüße,

Jan

**Comment by davidenke** [comment]
Hallo @jenda77,

die Nutzung von Unterordnern birgt gewisse Gefahren im Zusammenhang mit dem Newsletter-Versand und wurde deshalb bewusst entfernt: https://github.com/contao/core/issues/5379
Das Problem vererbt sich leider auch auf die Templates der Newsletter-Inhalte.

**Comment by jenda77** [comment]
Ok, wie ist es die Lösung?
