### ISSUE TITLE
Beim Template-Speichern Backend zerschossen

### ISSUE THREAD

**Issue by jenda77** [davidenke/newsletter_content#7]
Lieber David, 

ich habe noch eine Fehlermeldung. Sobald ich eine deiner Templates im BE bearbeite und danach speichere, wird das Backend zerschossen (siehe beigefügtes Bild). Das war schon vorher so. Woran kann es liegen? 

Liebe Grüße,
Jan
![bildschirmfoto 2015-05-19 um 13 26 16](https://cloud.githubusercontent.com/assets/3715050/7701779/d5af0638-fe2a-11e4-9a8a-02de5f4b470c.png)

**Comment by davidenke** [comment]
Womit bearbeitest du das Template? Was genau hast du geändert? Mit welcher Version der Erweiterung arbeitest du?

**Comment by jenda77** [comment]
Ich habe es dicht im BE bearbeitet. Ich arbeite mit der letzten Version, die du vor kurzem freigegeben hast. Im Hintergrund gibt es keine Fehlermeldungen, die ich vorher schon an hatte.

**Comment by davidenke** [comment]
Ich kann das leider mit aktueller Version und Contao 3.4.5 nicht nachvollziehen.
Was steht im Networkinspector? Hast du mal in der Systemwartung deine Caches geleert?

**Comment by jenda77** [comment]
Danke für deine schnelle Antwort. Welchen Networkinspektor meinst du? :-) Ja, das Cache habe ich schon mehrmals gelöscht, das brachte nichts. Kann es sein, dass es sich noch mit anderen Erweiterungen beißt.

**Comment by davidenke** [comment]
Im Safari, Firefox und Google Chrome gibt es Entwicklertools, welche die übertragenen Dateien mit ihrem Status listen.
Nebst der Leerung des Browsercache, bitte auch mal den Cache der Systemwartung leeren. Contao mal im abgesicherten Modus laufen lassen und schauen, was passiert. Danach mal Erweiterungen deaktivieren einzeln aktivieren und testen. Sollte es tatsächlich auf newsletter_content zurückzuführen sein, bitte in ein konkretisiertes Ticket.
